[package]
name = "tunnelblickctl"
version = "0.1.0"
authors = ["Ben Webber"]

[dependencies]
csv = "1.0.0-beta.4"
serde = "~1.0.0"
serde_derive = "~1.0.0"
tabwriter = "~1.0.0"

[dependencies.clap]
features = ["yaml"]
version = "~2.19.0"
